name: Rosario's Blog
description: Coding, startups and ideas.
meta_description: Rosario's Blog. Coding, startups and ideas.
date: 2012
permalink: /:year/:month/:day/:title

markdown: kramdown
highlighter: rouge

logo: false
paginate: 15
baseurl: ""
domain_name: "rosario.io"
google_analytics: "UA-31897052-1"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "/"
author: "Rosario Rascuna"
